### ISSUE TITLE
Class / property URI references do not work properly.

### ISSUE THREAD

**Issue by HaydarAk** [dgarijo/Widoco#407] opened 2020-06-15 14:51 UTC
Related to #192, I think

---

Direct URL links to ontology classes / properties of the widoco documentation, such as `http://localhost:8000#/myOntologyClass`  do not work properly.  Refs to sections, such as `http://localhost:8000#intro` still work. 

In my understanding, this is because the actual ontology class / property documentation is located in another file (`crossref-en.html`) and is loaded after loading the `index.html`. Therefore using, e.g. `http://localhost:8000#/myOntologyClass` can not be resolved. I assume this has to do with the following javascript code inside the `index.html`
```
$.fn.ignore = function(sel){
        return this.clone().find(sel||">*").remove().end();
 };    $(function(){
      $("#abstract").load("sections/abstract-en.html"); 
      $("#introduction").load("sections/introduction-en.html"); 
      $("#overview").load("sections/overview-en.html"); 
      $("#description").load("sections/description-en.html"); 
      $("#references").load("sections/references-en.html"); 
      $("#crossref").load("sections/crossref-en.html", null, loadHash); 
    });
    </script> 
```
After some testing on my local machine with a simple http server, I noticed that copying the contents of `crossref-en.html` into the `index.html` leads to proper results.

`http://localhost:8000/#/Resource` did not work for me, before. my browser landed on the head of my documentation. . 
After doing the above mentioned workaround, `http://localhost:8000/#/Resource` points me directly to the documentation of my ontology class `Resource`.

**Comment by dgarijo** [comment] 2020-06-15 16:02
@HaydarAk,

`http://localhost:8000/#/Resource` doesn't look right. It should be either `http://localhost:8000/#Resource` or `http://localhost:8000/Resource`. The fragment of the URI (after #) cannot have a "/", otherwise it won't work properly. 

What is the URI of the ontology you are trying to load? From what you have above, it is `http://localhost:8000/#/`, which is doesn't look right.

This functionality works fine because an ontology such as https://w3id.org/okn/o/sd#Software loads properly (I have done many other tests in slash and hash ontologies). Issue #192 is not related to this, as it refers to jumping sometimes to the wrong anchor in the JS.

**Comment by dgarijo** [comment] 2020-07-19 04:16
Since I cannot reproduce this issue, I will close it up. Please reopen as necessary.

On a side note, if your ontology has a slash, you may want to enable content negotiation based on slash ontologies, which is a little bit different from hash-based ontologies. See https://www.w3.org/TR/swbp-vocab-pub/

**Closed by dgarijo** 2020-07-19 04:16 UTC

**Comment by Zack-83** [comment] 2023-12-12 12:44
Hallo, possibly we have a case to reopen this issue.

A FOOPS! check of our ontology made us realize that the URIs of the single entries don't resolve to correct URLs. Luckily, they are resolved to the documentation page, but not to the right position.

As an example: the URI http://w3id.org/nfdi4ing/metadata4ing#hasAdmissibleUnit (with HTTP or HTTPS) is redirected to a nonexisting URL https://nfdi4ing.pages.rwth-aachen.de/metadata4ing/metadata4ing/index.html#hasAdmissibleUnit, which falls back to the top of the page <https://nfdi4ing.pages.rwth-aachen.de/metadata4ing/metadata4ing/index.html>.

The URL of the entry generated by Widoco is instead quite longer, to accommodate both for the ontology's own entries and those from the imported/extended ontologies: 
https://nfdi4ing.pages.rwth-aachen.de/metadata4ing/metadata4ing/index.html#http://w3id.org/nfdi4ing/metadata4ing#hasAdmissibleUnit.

Possibly our case is more complicated than usual, because we registered a [w3id](https://w3id.org/) domain, which resolves to the true documentation page. But that could also be the solution...

Present state:
```
<EntryURI> = <BaseURI>#<EntryID> -->Widoco--> <EntryDocumentationURL> = <BaseURL>#<BaseURI>#<EntryID>
                                          --> <EntryResolvedURL>      = <BaseURL>#<EntryID>
```
Should be: `<EntryResolvedURL> = <EntryDocumentationURL>`.

Possible solutions:
- shorten `<EntryDocumentationURL>`
- lengthen `<EntryResolvedURL>`
- choose an intermediate form, such as `<BaseURL>#prefix:<EntryID>`
- attach an anchor in the HTML output also to the second '#'
- ...

**Comment by dgarijo** [comment] 2023-12-12 13:14
Hello,
I think this is not a problem of the tool. See for example `https://w3id.org/example#Organization`, it will redirect to the specific part of the page. If you look at the div ids of the document I used, the id is local, i.e., `id="Organization"`.

However, in yours, the id is `http://w3id.org/nfdi4ing/metadata4ing#hasAdmissibleUnit` for the div. This happens when you are referring to external URLs. What I think it's happening here is that you have not configured your local id (the URI of the ontology) in the tool, and therefore it thinks that your ids are external. 

Therefore, the URI `http://w3id.org/nfdi4ing/metadata4ing#http://w3id.org/nfdi4ing/metadata4ing#hasAdmissibleUnit` is the one that works in your case. I recommend regenerating the doc using the `preferredNamespaceUri` from `vann` to address this issue. Or to edit manually your html removing the `#http://w3id.org/nfdi4ing/metadata4ing` from html ids.

**Comment by Zack-83** [comment] 2023-12-12 13:43
Actually we did add a [`vann:preferredNameSpaceUri`](https://git.rwth-aachen.de/nfdi4ing/metadata4ing/metadata4ing/-/blob/190-suggestions-foops-check/metadata4ing.ttl#L30). Does it make a difference if the range is enclosed between quotes "" or acute brackets <>? 

If yes, then your documentation ([best practice guide](https://dgarijo.github.io/Widoco/doc/bestPractices/index-en.html#namespaceURI), [metadata guide](https://github.com/dgarijo/Widoco/blob/master/doc/metadataGuide/guide.md#user-content-onto)) contains the same mistake.

**Comment by dgarijo** [comment] 2023-12-12 15:04
In theory it should be between quotes (a literal), not a resource. Make sure you include the hash/slash ending, just in case.
