### ISSUE TITLE
widoco gives me empty doc

### ISSUE THREAD

**Issue by saidfathalla** [dgarijo/Widoco#366] opened 2019-09-18 13:37 UTC
I am running Win 8.1 with Java 1.8 and widoco gives me empty doc. however it works in my friend's machine. can you help me?
we are use the same version.

**Comment by dgarijo** [comment] 2019-09-18 16:28
Without a pointer to the ontology, it's impossible for me to figure out this issue.
Have you verified that this is not caused by this issue? https://github.com/dgarijo/Widoco#browser-issues
In the latest updates, firefox also prevents from showing the results in your local computer, but will work fine when uploading it to a server

**Comment by rduerr** [comment] 2019-09-27 21:31
I have the same problem with macOS Mojave Version 10.14.6 running with the latest version of java. My file is at https://github.com/earthcubearchitecture-ecresourcereg/Utility-Ontologies/blob/master/ADO.rdf.

I also note that both of the Important "issues" found by OOPS! are not real...

**Comment by dgarijo** [comment] 2019-09-27 23:10
Hi, just to clarify,
The document will work properly when hosted on a server. It just cannot be
viewed locally due to recent security updates of the browsers. See the main
readme file in the Widoco repository for more details.

As for the issues detected by OOPS!, what do you mean the issues are not
real? Do you mean they don't exist, or you don't consider issues? If the
latter, then you can consider them suggestions. I have not created OOPS! I
just integrated it into the tool.

**Comment by rduerr** [comment] 2019-09-30 18:23
Hi Daniel,

Well, not having a server (would hosting on GitHub count?), that leaves me rather stuck and unable to use this tool (sigh…).  

Also, is this a EarthCube product?  If so, we ought to get it registered.

Ruth

**Comment by dgarijo** [comment] 2019-09-30 18:51
Hi @rduerr,

You can host it in GitHub through a GitHub Page. I host most of my ontology documentations this way. For example: https://knowledgecaptureanddiscovery.github.io/SoftwareDescriptionOntology/release/1.1.0/index-en.html. You just have to configure it on your github repository settings.

Note that in the example I posted all sections can be seen properly. The tool aims at creating HTML representations so they can be used through a web browser, so if your aim is not for others to see your documentation through a web page, then WIDOCO may not be the right tool for you.

I am creating a version of WIDOCO that will allow you having all the sections embedded in the main HTML. This will allow you to see it locally (except the WebVowl visualization, which has similar problems), but it will be more difficult to manage because you end up with 1 giant document instead of 5 or 6. 

Finally, no, it's not an EarthCube product. I created it in my free time :)
Thanks for trying WIDOCO out!

**Comment by rduerr** [comment] 2019-09-30 18:55
@dgarijo Thanks!  I'll try that out.

**Comment by dgarijo** [comment] 2019-10-27 03:48
Given that this issue seems to be solved, I will close it.

**Closed by dgarijo** 2019-10-27 03:48 UTC
