### ISSUE TITLE
Scrolling to WebVOWL on Page Load

### ISSUE THREAD

**Issue by nicholsn** [dgarijo/Widoco#354] opened 2019-06-20 11:43 UTC
With `widoco-1.4.10-jar-with-dependencies.jar`, on page load the focus moves down to the WebVOWL visualization rather than staying at the top of the page.

This may be related to #110 

Is there a way to force widoco to load the documentation and stay focused at the top of the screen?

**Comment by dgarijo** [comment] 2019-06-20 14:57
I can't reproduce the issue. I have tested it out with 1.4.11 and the page seems generated fine.
By default the page will be loaded with the focus on top, unless you load an anchor.
Can you try with 1.4.11 and see if the problem persists? If so, can you share the URL here?

**Comment by nicholsn** [comment] 2019-06-20 17:14
I don't have a public site for this, but just using a public ontology I also see the issue with 1.4.11 on a Macbook in Chrome Version 75.0.3770.90 (Official Build) (64-bit). I only see the issue when Webvowl is enabled.

If I look in the web console during page load, I see:

```
webvowl/index.html#:10 The key "" is not recognized and ignored.
webvowl.app.js:1 Browser Version =-1
```

And here is how I am building the docs:
```
(base) ✔ ~/Downloads/widodo
10:07 $ http https://www.w3.org/ns/prov# Accept:text/turtle --verify=false > prov.ttl
(base) ✔ ~/Downloads/widodo
10:07 $ java -jar widoco-1.4.11-jar-with-dependencies.jar -ontFile prov.ttl -webVowl
log4j:WARN No appenders could be found for logger (widoco.gui.GuiController).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
Documentation generated successfully
(base) ✔ ~/Downloads/widodo
10:07 $ python -m http.server
Serving HTTP on 0.0.0.0 port 8000 (http://0.0.0.0:8000/) ...
```

**Comment by dgarijo** [comment] 2019-06-20 20:07
I have been able to reproduce it in chrome. In Firefox it works okay. It may be something regarding the browser options, but I will have to look in detail

**Comment by pmcb55** [comment] 2019-07-20 16:08
Yeah, I'm seeing this same behaviour on Chrome too. Any update on a possible fix for this one??

**Comment by dgarijo** [comment] 2019-07-20 18:57
It's not straightforward because it doesn't depend on what I generate, but on how Chrome interprets it. Help is welcome  :)

**Comment by pmcb55** [comment] 2019-07-21 10:51
@dgarijo So I submitted a PR that fixes this for me (@nicholsn that startup error you see `webvowl/index.html#:10 The key "" is not recognized and ignored.` is annoying, but is just caused by a trailing comma in the generated code, and isn't related to the WebVOWL scrolling problem). I had a quick look at fixed that error too, but it seems that the generated code is somehow appending extra values, but isn't removing the trialing comma after the last value (it's a fiddly problem in general when appending to lists!).

**Comment by nicholsn** [comment] 2019-08-01 23:18
thanks @pmcb55! that worked for me. I'll leave this open until there is a release that incorporates this in master at https://github.com/dgarijo/Widoco/blob/master/src/main/java/widoco/CreateResources.java#L267

**Comment by dgarijo** [comment] 2019-08-02 03:26
Yeah, please keep it open. I will close it on the next release (hopefully soon) :)

**Closed** 2019-10-27 03:41 UTC
