### ISSUE TITLE
WebVOWL issue

### ISSUE THREAD

**Issue by biswanathdutta** [dgarijo/Widoco#338] opened 2019-03-25 11:18 UTC
WebVOWL 1.1.2 of Widoco 1.4.9 is failing to load OWL Ontology. It shows: "Failed to load: Ontology STATUS 0" 
Is this a bug? Or, some other issue?

**Comment by dgarijo** [comment] 2019-03-25 17:13
Which ontology is it failing for? 

For me it works quite nicely. See https://mintproject.github.io/Mint-ModelCatalog-Ontology/modelCatalog/release/0.4.0/index-en.html

Note that WebOWL only works with OWL ontologies

**Comment by biswanathdutta** [comment] 2019-03-26 03:09
Thanks for the reply. 
I am also trying with OWL ontology only. Earlier also used the tool without any problem. But this time for some unknown reason, WebVOWL is failing to display the ontology. 

BTW, are there any other constraints (besides that the tool works only with owl ontology) in using the WebVOWL?

**Comment by dgarijo** [comment] 2019-03-26 18:53
Not as far as I know.
If you don't share the ontology here, I cannot help you address this issue :(
Therefore, if I cannot reproduce the issue I will end up closing it after a while.

**Comment by biswanathdutta** [comment] 2019-03-27 09:30
Yes, may close the issue, at this time, I have generated the vocabulary Specification Document without the WebVOWL. 
Here is the document: https://www.isibang.ac.in/ns/mod 

The Widoco versions 1.4.4 and 1.4.5 remained silent for the Ontology (the Ontology is available from the above page). I have used 1.4.9. 
Thanks,

**Comment by biswanathdutta** [comment] 2019-03-28 04:31
For my current owl ontology, none of the Widoco versions is able to produce WebVOWL view. 

The Widoco versions 1.4.4 and 1.4.5 are unable to generate even the Specification document (HTML). 

I have used version 1.4.9 to produce the document you see here (deselecting the WebVOWL view): https://www.isibang.ac.in/ns/mod 

Thanks

**Comment by dgarijo** [comment] 2019-03-28 16:36
Unfortunately WebVOWL is a little out of my reach. I suggest you to create an issue in their repository. Probably the tool gets confused because some of the properties you are defining as object properties are usually used as annotation properties.
I will close this issue.

**Closed by dgarijo** 2019-03-28 16:36 UTC
