### ISSUE TITLE
List of namespaces generated without the "/" or "#"

### ISSUE THREAD

**Issue by ednaru** [dgarijo/Widoco#640] opened 2023-10-16 08:42 UTC
**Describe the bug**
The namespaces in the documentation are generated without the corresponding "/" or "#" that are present in the ontology file.

**To Reproduce**
1. Go to '[ontology](https://data-interop.era.europa.eu/era-vocabulary/)'
2. Scroll down to '1.1 Namesoace declarations'
3. See for example, <http://www.w3.org/2000/01/rdf-schema>
4. Click on '[ontology file](https://data-interop.era.europa.eu/era-vocabulary/ontology.ttl)'
5. You can see that the file contains "@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>"

**Expected behavior**
The Namespace declarations should contain the corrresponding "#" or "/". Currently, the documentation is tweaked by hand.

**Comment by dgarijo** [comment] 2024-04-04 17:33
@ednaru I cannot reproduce this issue. I generated the following HTML table from that ontology:
```
[Ontology NS Prefix]	<http://data.europa.eu/949/>
dc	<http://purl.org/dc/elements/1.1/>
foaf	<http://xmlns.com/foaf/0.1/>
geosparql	<http://www.opengis.net/ont/geosparql#>
ns	<http://creativecommons.org/ns#>
ns1	<http://www.w3.org/2003/06/sw-vocab-status/ns#>
op-types	<http://data.europa.eu/949/concepts/op-types/>
org	<http://www.w3.org/ns/org#>
owl	<http://www.w3.org/2002/07/owl#>
rdf	<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs	<http://www.w3.org/2000/01/rdf-schema#>
schema	<http://schema.org/>
skos	<http://www.w3.org/2004/02/skos/core#>
terms	<http://purl.org/dc/terms/>
wgs84_pos	<http://www.w3.org/2003/01/geo/wgs84_pos#>
xml	<http://www.w3.org/XML/1998/namespace>
xsd	<http://www.w3.org/2001/XMLSchema#>
```
All contain the corresponding ending. I will close the issue.

**Closed by dgarijo** 2024-04-04 17:33 UTC
Labels: enhancement
