### ISSUE TITLE
The GUI does not show up on Mac OS 10.15.5

### ISSUE THREAD

**Issue by lucaturchet** [dgarijo/Widoco#419] opened 2020-08-02 16:10 UTC
**Describe the bug**
The GUI does not show up on Mac OS 10.15.5

**To Reproduce**
I downloaded the lates java jre and the latest stable release.

**Expected behavior**
As far as I remember from previous uses there was a GUI, now this GUI does not appear.

**Note**
This issue applies only to the lastest stable release. In the pre-release widoco-1.4.15-jar-with-dependencies the issue is not present, the GUI shows up correctly

**Comment by dgarijo** [comment] 2020-08-02 18:16
I need more details to reproduce/figure out what this issue could be (I don't own a mac):

1) Do you see anything when opening the GUI in the command line? (that is, executing `java -jar widoco....jar`)
2) Do you have Java 8 installed? Maybe the JRE you downloaded is not appropriately configured.
3) Does WIDOCO work through the command line?

**Comment by dgarijo** [comment] 2020-08-02 18:18
Oh, so then the issue may have been solved already :)

**Comment by dgarijo** [comment] 2020-08-02 18:20
I will leave this issue up until version 1.4.15 is released.

**Comment by dgarijo** [comment] 2021-12-20 11:16
Closing because 1.4.15 has already been released. Feel free to reopen if appropriate.

**Closed** 2021-12-20 11:16 UTC
