### ISSUE TITLE
Custom Styles and Documentation sections

### ISSUE THREAD

**Issue by kleegrewec** [dgarijo/Widoco#402] opened 2020-06-04 14:58 UTC
Dear widoco team.

We are using widoco to generate documentation for some ontologies that are related to our application domain. We have a company git repository where the ontologies are developed and we use a ci/cd pipeline to automatically generate documentation on each push at the master branch. Regarding generation of documentation we have the following questions:
To ease the application of the ontologies for the user we would like to add a section with examples and code snippets on ontology usage to each documentation html page. Is there some best practices available how to do this? or is there a built in mechanism to define additional sections and content for the generated html?
In addition to give the documentation some special look we want to use custom styles. As of the widoco git page we know that this is possible by using the -useCustomStyle switch but we could not find any documentation about how to make the custom sheets available to the widoco jar file. Are we missing anything here? Please send information how to apply custom styles.

thanks in advance, Christian

**Comment by dgarijo** [comment] 2020-06-06 03:18
Hi Christian,
If you want to add examples to terms, you may do so by annotating the terms in the ontology with
http://purl.org/vocab/vann/example. Here is an example of how WIDOCO will list them:

![image](https://user-images.githubusercontent.com/1520666/83934908-18efe100-a769-11ea-9de3-3f5084a754d2.png)

(You don't need to add a URL, an example can be text if you want)

If you want to add them in a section, I would suggest using the "description" section in the HTML. I always put usage examples there. See http://linked.earth/ontology/core/1.2.0/index-en.html#desc as an example.

Regarding the `-useCustomStyle`, maybe this flag is a little misleading. It doesn't mean that you can use your own style, it means that the documentation will be generated following a different style. In particular [this one](http://datos.bne.es/def/ontology.html). If you want to rewrite your own style you have to change the css used by Widoco. They are generated along with the documentation in the resources folder:
![image](https://user-images.githubusercontent.com/1520666/83934972-bd722300-a769-11ea-962d-4005c426410e.png)

**Comment by dgarijo** [comment] 2020-06-06 03:19
Since this issue is not a bug or a feature request and has been answered, I will close it.

**Closed by dgarijo** 2020-06-06 03:19 UTC
