### ISSUE TITLE
Incorrectly populated fields in OOPS! evaluation report.

### ISSUE THREAD

**Issue by nandana** [dgarijo/Widoco#178] opened 2016-06-30 08:21 UTC
In the report generated by Ontoology, the ontology name and URI is not correctly populated. 

References:
[GitHub Issue](https://github.com/nandana/loupe-ontology/issues/9)
[Evaluation Report](https://cdn.rawgit.com/nandana/loupe-ontology/df2971a5df4ca0d7f6a78ce8446a4c4805404fc9/OnToology/OnToology/src/ontology/loupe-ontology.owl/documentation/ontology.owl/evaluation/oopsEval.html) 
[Ontology](https://cdn.rawgit.com/nandana/loupe-ontology/fae82d595388ba4c79863709b45face8f091b9d2/src/ontology/loupe-ontology.owl)
[Widoco Config](https://cdn.rawgit.com/nandana/loupe-ontology/fae82d595388ba4c79863709b45face8f091b9d2/OnToology/src/ontology/loupe-ontology.owl/documentation/loupe-ontology.owl.widoco.conf)

**Comment by dgarijo** [comment] 2016-07-06 16:15
I cannot reproduce this issue. I have tried the configuration file but get the right html (see below). This must be due to OnToology using an old version of Widoco. Have you tried doing this with Widoco? directly?
I will close the issue for the moment.
![loupe](https://cloud.githubusercontent.com/assets/1520666/16625605/ac4f1802-43a5-11e6-9a29-9fe00d96f025.png)

**Closed by dgarijo** 2016-07-06 16:15 UTC
