### ISSUE TITLE
Removing Webvowl

### ISSUE THREAD

**Issue by kmcglinn** [dgarijo/Widoco#370] opened 2019-12-13 11:46 UTC
I ticked the "no link for WebvOWL" in the configuration box for WIDICO. Unfortunately, I am left with a big empty box. I assume I have to remove a tag in the html or edit the JS, is that correct?

Kind regards,

Kris.

**Comment by dgarijo** [comment] 2019-12-13 18:29
Oops, I think I may have forgotten to remove the space for the image in the HTML. I will check this out and fix it in the next release. In the meantime, yes, you can edit the HTML and edit it

**Comment by kmcglinn** [comment] 2019-12-16 10:33
Thanks for your speedy reply. I found the iframe in the overview section. I removed this, but still getting the same "url not found" box. Any other pointers to remove this?

Here is the link - https://www.scss.tcd.ie/~mcglink/ontologies/geoff/index-en.html

**Comment by dgarijo** [comment] 2019-12-16 19:29
I see it correctly, with no image box. Have you refreshed the cache on your browser (or try it with an incognito mode)? Sometimes it shows a previous version even after updating the github page.

**Comment by kmcglinn** [comment] 2019-12-18 10:06
Hi Daniel,

Thanks, you are correct! :)

Best,

Kris.

**Comment by dgarijo** [comment] 2020-01-12 21:21
@kmcglinn, I have double checked and this case is handled correctly by the app. I Unclicked the box and the iframe with the image is not added, which is the right behavior.

Since I cannot reproduce this issue, I will close it. Please reopen if you experience this again. If so, please specify version of WIDOCO and the ontology you have tried, so I can reproduce the error. Thanks!

**Closed by dgarijo** 2020-01-12 21:21 UTC
Labels: bug, pressing
