### ISSUE TITLE
Document Not produced for imported ontologies

### ISSUE THREAD

**Issue by kartgk** [dgarijo/Widoco#246] opened 2017-07-12 09:50 UTC
I am trying to generate lode documentation including imported ontologies by using --includeImportedOntologies, but it is not working. Attaching a basic ontology file which imports provenance and time ontologies. When I checked against the http://www.essepuntato.it/lode  the documentation is getting generated properly.
[yyyy-core.txt](https://github.com/dgarijo/Widoco/files/1141569/yyyy-core.txt)

**Comment by dgarijo** [comment] 2017-07-12 19:35
@kartgk,
thanks for your issue, but I cannot reproduce it. I downloaded the ontology and executed it with: java -jar widoco-1.4.1-jar-with-dependencies.jar -ontFile testOntos/yyyy-core.ttl -outFolder doc  -rewriteAll -lang en -includeImportedOntologies -getOntologyMetadata -licensius -webVowl 

And I got the documentation generated successfully (see attached file)
[doc.zip](https://github.com/dgarijo/Widoco/files/1143107/doc.zip)

As you can see, the documentation contains the imported PROV and time. Did you get an error? note that you should use a single dash ( -includeImportedOntologies)

**Comment by kartgk** [comment] 2017-07-13 05:54
@dgarijo 
Thanks for checking it out.
I tried again. I downloaded the jar from https://github.com/dgarijo/Widoco/releases/download/v1.4.1/widoco-1.4.1-jar-with-dependencies.jar
Still I dont get the provenance and time documentation.  I get some errors, see attached jpeg.
![yyyy-cmd-output](https://user-images.githubusercontent.com/12909601/28152341-83c7cfae-67bd-11e7-844b-02ff3d5aacb6.jpg)
I am not using any config.properties.
This is my command line
java -jar widoco-1.4.1-jar-with-dependencies.jar -ontFile yyyy-core.ttl -outFolder doc -rewriteAll -lang en -includeImportedOntologies -getOntologyMetadata -licensius -webVowl

**Comment by dgarijo** [comment] 2017-07-13 06:01
@kartgk,
I have executed exactly those steps and I get the same console log with the documentation successfully generated. See attached screenshot: 
![image](https://user-images.githubusercontent.com/1520666/28152523-d3d4909e-6755-11e7-8560-8690815a94b9.png)

It's ok if you don't use any config.properties.
The documentation of both ontologies will be included in your HTML, it won't be separated as different documentations.

**Comment by kartgk** [comment] 2017-07-13 06:16
@dgarijo I repeated the same on my MAC and it is working fine.

 I see that on my windows output I get the below error and guess probably same issue is preventing other ontologies being loaded.

http://www.licensius.com/api/license/findlicenseinrdf?uri=https%3A%2F%2Fdata.xxxx.xxxx%2Fowl%2Fyyyy-core
-->Could not load license for vocab: connect timed out

**Closed** 2018-04-16 02:53 UTC
Labels: bug
