### ISSUE TITLE
Imported Ontologies Section is not getting generated

### ISSUE THREAD

**Issue by kartgk** [dgarijo/Widoco#284] opened 2018-04-11 07:02 UTC
Please find attached the ontology file. 
[CorporateBodies.txt](https://github.com/dgarijo/Widoco/files/1897589/CorporateBodies.txt)

java -jar ./widoco-1.4.2-jar-with-dependencies.jar -ontFile "CorporateBodies.rdf" -outFolder "CorporateBodies" -lang en -includeImportedOntologies -rewriteAll  -getOntologyMetadata -webVowl -licensius

The generated index html file doesnt have the imported ontologies section. Can you please advice.

**Comment by dgarijo** [comment] 2018-04-12 21:50
I have been able to reproduce the issue. Thanks for reporting it!
I will try to have a look at this soon.

**Comment by jgeluk** [comment] 2019-01-09 13:48
We're still having this issue, slightly different perhaps, rather than not showing any imported ontologis it shows only one.

**Comment by dgarijo** [comment] 2020-07-19 21:34
I have done some digging into this problem. I have uploaded https://github.com/dgarijo/Widoco/blob/develop/test/multipleImports.owl which imports three different ontologies; and the sections get generated. I have also done some tests:
- If one of the imports didn't resolve
- If there is a difference adding the ontologies in the same document or not
- Adding imports that import other ontologies.

As you can see, with the test file, the section is generated automatically for all three ontologies:

![image](https://user-images.githubusercontent.com/1520666/87885627-2df89a80-c9cc-11ea-931b-afc0753dccaf.png)

In the `corporate bodies ontology` I believe it's failing because the imports do not resolve properly. WIDOCO fails silently when an import fails, because the assumption is that it's better to generate some documentation than having none.

I tried the provided ontology in Protege too, and the documents got imported with errors as well. I believe that if the import errors are addressed, everything should work correctly. I am closing the issue, but feel free to reopen if you consider it necessary.

**Closed by dgarijo** 2020-07-19 21:34 UTC
Labels: bug
