### ISSUE TITLE
VOWL panel not working

### ISSUE THREAD

**Issue by mlaura1996** [dgarijo/Widoco#683] opened 2024-04-01 10:22 UTC
Dear all, 
I am using widoco for representing my ontology. Everything looks fine, except for the vowl interface

![image](https://github.com/dgarijo/Widoco/assets/99893051/401c07e7-d948-408f-810c-bfa97adad6c9)

does someone encountered the same issue?

**Comment by dgarijo** [comment] 2024-04-01 14:01
@mlaura1996 this looks like you have not published the page online, but you have just opened it locally with your browser. Once you put the documentation on a server, or in a github page, it will render fine.

See https://github.com/dgarijo/Widoco?tab=readme-ov-file#browser-issues-why-cant-i-see-the-generated-documentation--visualization for more information.

If once you put it online it still does not work, please share the ontology here so I can reproduce the issue. 
In the meantime, I will close this issue (feel free to reopen it if the problem persists). Thanks!

**Closed by dgarijo** 2024-04-01 14:01 UTC
